

GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiU2hpYnUzIiwiaWF0IjoxNzQ4MzY5MTExLCJleHAiOjE3NDgzNjkxMzF9.MQOp7BB42djg4A-NByCAJjZ2x-APsj3w4fJE_jdlnhc

###


DELETE http://localhost:4000/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiU2hpYnUzIiwiaWF0IjoxNzQ4MzY5MDMwfQ.ntIAxYMpQAlByBJ5ci770HiCsV34EJDDxjP3oy4jpCM"

}


###

POST http://localhost:4000/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiU2hpYnUzIiwiaWF0IjoxNzQ4MzY5MDMwfQ.ntIAxYMpQAlByBJ5ci770HiCsV34EJDDxjP3oy4jpCM"

}

###


POST http://localhost:4000/login
Content-Type: application/json

{
  "username": "Shibu3"
}

